# .github/workflows/deploy.yml
name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    - name: Install Trunk
      run: cargo install --locked trunk
    
    - name: Build Conway's Game of Life
      run: |
        cd CGoL-Rust/
        trunk build --release --public-url /
    
    - name: Prepare deployment
      run: |
        mkdir -p dist
        cp -r CGoL-Rust/dist/* dist/
        cp CNAME dist/
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

